language: php

php:
    - 7.0
    - 7.4
    - 8.0

matrix:
    allow_failures:
        - php: 7.0
        - php: 8.0
    fast_finish: true

services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.cache/phpcs

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64 --output php-security-checker
    - chmod 755 ./php-security-checker

install:
    - travis_retry composer install -a --working-dir=tools/php_codesniffer --ignore-platform-reqs
    - travis_retry composer install -a --no-scripts
    - travis_retry composer install -a --working-dir=tools/php-scoper
    - composer prefix-deps

before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS oneid_wordpress_plugin_test;'
    - mkdir -p $HOME/.cache/phpcs/

script:
    - composer check-platform-reqs --no-dev
    - ./tools/php_codesniffer/vendor/bin/phpcs . --severity=1 --cache=$HOME/.cache/phpcs/phpcs.json
    - ./php-security-checker
    - composer test:unit
    - composer test:integration
